# Generated by Django 3.2.3 on 2021-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BathPersonalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.IntegerField(default=0, null=True)),
                ('img_src', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('rating', models.CharField(blank=True, default='', max_length=20)),
                ('reviews', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=20)),
                ('link', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'bath_personal_products',
            },
        ),
    ]
